name: 'ci'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Set Bun Path
        run: echo "::add-path::$(bun env | grep BUN_INSTALL | cut -d'=' -f2)/bin"

      - name: Install Dependencies
        run: bun install --no-save # 不依赖 lock 文件安装

      - name: Run Prettier
        run: bun run format