name: autofix.ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write # 允许推送更改回 PR 分支

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier Check
        run: npm run format:check

      - name: Fix Prettier Issues (if any)
        run: |
          npm run format
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: fix formatting issues" || echo "No changes to commit"
          git push || echo "No changes to push"