name: autofix.ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm' # 启用 pnpm 缓存以加速依赖安装

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Prettier Check
        run: pnpm run format:check
